apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: device-connection-report
  labels:
    app: device-connection-report
  namespace: data
spec:
  # suspend: true
  schedule: "0 17 * * *"   
  # schedule: "*/5 * * * *"   # every 5 mins
  # 
  # +---------------- minute (0 - 59)
  # |  +------------- hour (0 - 23)
  # |  |  +---------- day of month (1 - 31)
  # |  |  |  +------- month (1 - 12)
  # |  |  |  |  +---- day of week (0 - 6) (Sunday=0 or 7)
  # |  |  |  |  |
  # *  *  *  *  *  command to be executed
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          name: device-connection-report
          labels:
            app: device-connection-report
        spec:
          containers:
          - name: device-connection-report
            image: gcr.io/alfred-recruitment-test/datapipeline:v1.0
            command: ["/bin/bash","-c"]
            args:
            - . worker.sh
            env:
            - name: FLOW_NAME
              value: "DeviceConnectionDailyFlow"
            - name: PROJECT_ID
              value: "alfred-recruitment-test"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secret/gcloud-credential.json"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            imagePullPolicy: IfNotPresent   #Always
            resources:
              requests:
                cpu: 400m
                memory: 500Mi
              limits:
                cpu: 1000m
                memory: 1000Mi
            volumeMounts:
            - mountPath: /secret
              name: gcloud-credential
              readOnly: true
          restartPolicy: Never #OnFailure
          volumes:
            - name: gcloud-credential
              secret:
                defaultMode: 420
                secretName: gcloud-credential
